# configs of task and path
task: 'gastric_esd_subtype'
data_root_dir: '/home3/gzy/Gastric_ESD/feature_resnet/'
exp_code: 'gastric_esd_subtyping_abmil_w'


label_frac: 1
results_dir: './results'


# configs of training
seed: 1
k: 5
k_start: 0
k_end: 5
max_epochs: 200
lr: 0.0001
reg: 0.00001
early_stopping: True
drop_out: True
drop_rate: 0.25
opt: 'adam'
bag_loss: 'bce'
weighted_sample: True
log_data:  True
testing: False

# configs of model
model_type: 'clam_mb'
model_size: 'small' # 'big'
fea_dim: 1024  # 512
inst_rate: 0.1
no_inst_cluster:  True
inst_loss:  None
subtyping:  True
bag_weight:  0.7
B:  8